sonar.projectKey=al1ya_exa-gate
sonar.organization=al1ya
sonar.projectName=Exa Gate
sonar.projectVersion=2.1.0

# Sources
sonar.sources=cmd,internal
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=internal/adminapi/console/**,**/*_test.go

# Go
sonar.go.file.suffixes=.go

# Encoding
sonar.sourceEncoding=UTF-8

sonar.host.url=https://sonarcloud.io
